name: Pandoc

on: [push, pull_request]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:latest
        with:
          args: --filter pandoc-citeproc plan.md -o plan.pdf
      - uses: actions/upload-artifact@master
        with:
          name: plan.pdf
          path: plan.pdf

