name: Pandoc

on: [push, pull_request]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install python-gantt
      - run: make gantt.svg
      - uses: docker://carmenbianca/pandoc:latest
        with:
          args: make
      - uses: actions/upload-artifact@master
        with:
          name: plan.pdf
          path: plan.pdf

